#!/bin/bash
# Scheduling program for personal use. Copy paste of journal.
# BSD/MacOS specific due to GNU vs BSD date implementation.
# usage: journal [read/today/tomorrow/yesterday/week/etc.]
# Jefferson Chen

# print usage
printUsage () {
  echo
  echo "    usage: schedule [option]"
  echo "        read:      list view of all schedule entries"
  echo "        today:     today's schedule"
  echo "        tomrrow:   tomorrow's schedule"
  echo "        yesterday: yesterday's schedule"
  echo "        week:      this week's schedule"
  echo
}

SCHEDULE_DIR="/Users/jeffkipp/Table/Personal/Schedules"

## START ##

# check has one arg
if [ $# != 1 ]; then
  printUsage
  exit 1
fi

# process read flag
if [ $1 == read ]; then
  vim "$SCHEDULE_DIR"
  exit 0
fi

# today flag
if [ $1 == today ]; then
  touch "$SCHEDULE_DIR"/`date +"%y.%m.%d"`\ Schedule.txt
  vim "$SCHEDULE_DIR"/`date +"%y.%m.%d"`\ Schedule.txt
  exit 0
fi

# tomorrow flag
if [ $1 == tomorrow ]; then
  touch "$SCHEDULE_DIR"/`date -v +1d +"%y.%m.%d"`\ Schedule.txt
  vim "$SCHEDULE_DIR"/`date -v +1d +"%y.%m.%d"`\ Schedule.txt
  exit 0
fi

# yesterday flag
if [ $1 == yesterday ]; then
  touch "$SCHEDULE_DIR"/`date -v -1d +"%y.%m.%d"`\ Schedule.txt
  vim "$SCHEDULE_DIR"/`date -v -1d +"%y.%m.%d"`\ Schedule.txt
  exit 0
fi

# week flag
if [ $1 == week ]; then
  touch "$SCHEDULE_DIR"/`date -v -sat +"%y.%m.%d"`\ Week\ Schedule.txt
  vim "$SCHEDULE_DIR"/`date -v -sat +"%y.%m.%d"`\ Week\ Schedule.txt
  exit 0
fi

# unrecognized flag; error
echo "error: unrecognzed flag"
printUsage
exit 2

# DID
# wrote draft
# debugged touch not working - has to use full path to file
# added tomorrow, yesterday, and week functionality
#  copy pasted from faulty Today

# TODO (mostly cleanup)
# support abbreviated day names
# default journal headers
# make date format changeable
# make easier to read
# make journal identifier format changeable (just const)
# make weeek journal identifier format changeable (just const)
# clean up variables

# FEATURES (things that I'll likely never need)
# document exit codes
# add readall functionality
