#!/bin/bash

###
# Program to set up a git repository. 
# credit: defualt GitHub things, slightly modified for blank README
###
git init
touch README.md
git add README.md
git commit -m "first commit"
git remote add origin git@github.com:jeffersonKipp/bin.git
git push -u origin master
