#!/bin/bash

echo -n "site: "
read SITE
echo -n "domain: "
read DOMAIN

wget \
		--recursive \
		--no-clobber \
		--page-requisites \
		--html-extension \
		--convert-links \
		--domains ${DOMAIN} \
		${SITE}
