#!/bin/bash

###
# Program that downloads a site. Asks for the site to download and
# the domain to restrict the program to.
###
echo -n "site: "
read SITE
echo -n "domain: "
read DOMAIN

wget \
		--recursive \
		--no-clobber \
		--page-requisites \
		--html-extension \
		--convert-links \
		--domains ${DOMAIN} \
		${SITE}
